# Generated by Django 4.2.6 on 2023-10-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inmakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=250)),
                ('ig', models.ImageField(upload_to='pics')),

            ],
        ),
    ]
